(asdf:load-asd (truename "foldback.asd"))
(ql:quickload :foldback)
(ql:quickload :fset)

(in-package #:foldback)

(defun test-jnb-gravity ()
  (format t "~%Testing Jump and Bump Gravity (Lisp)...~%")
  (let* ((p0 (make-jnb-player :x 100000 :y 0 :vx 0 :vy 0 :h 100))
         (s0 (initial-state))
         (s0 (fset:with s0 :players (fset:map (0 p0))))
         (s1 (jnb-update s0 (fset:map)))
         (p1 (fset:lookup (fset:lookup s1 :players) 0)))
    
    (format t "  Result: y=~A, vy=~A~%" (fset:lookup p1 :y) (fset:lookup p1 :vy))
    (assert (> (fset:lookup p1 :vy) 0))
    (assert (> (fset:lookup p1 :y) 0))
    (format t "  PASS: Gravity applied~%")))

(defun test-jnb-squish ()
  (format t "~%Testing Jump and Bump Squish (Lisp)...~%")
  (let* ((p1 (make-jnb-player :x 100000 :y 90000 :vx 0 :vy 1000 :h 100))
         (p2 (make-jnb-player :x 100000 :y 100000 :vx 0 :vy 0 :h 100))
         (s0 (initial-state))
         (s0 (fset:with s0 :players (fset:map (0 p1) (1 p2))))
         (s1 (jnb-update s0 (fset:map)))
         (p1-after (fset:lookup (fset:lookup s1 :players) 0))
         (p2-after (fset:lookup (fset:lookup s1 :players) 1)))
    
    (format t "  P1: y=~A, vy=~A | P2: h=~A~%" 
            (fset:lookup p1-after :y) (fset:lookup p1-after :vy) (fset:lookup p2-after :h))
    
    (assert (= (fset:lookup p2-after :h) 0))
    (assert (< (fset:lookup p1-after :vy) 0)) ;; Bounced up
    (format t "  PASS: P1 squished P2 and bounced~%")))

(defun test-jnb-respawn ()
  (format t "~%Testing Jump and Bump Respawn Determinism (Lisp)...~%")
  (let* ((p0 (make-jnb-player :x 100000 :y 100000 :vx 0 :vy 0 :h 0))
         (s0 (initial-state :custom-state (fset:map (:seed 123))))
         (s0 (fset:with s0 :players (fset:map (0 p0))))
         (s1 (jnb-update s0 (fset:map)))
         (players-after (fset:lookup s1 :players))
         (p-after (fset:lookup players-after 0))
         (custom-after (fset:lookup s1 :custom-state))
         (seed-after (fset:lookup custom-after :seed)))
    
    (format t "  P0 Respawn: x=~A, y=~A, d=~A, seed=~A~%" 
            (fset:lookup p-after :x) (fset:lookup p-after :y) (fset:lookup p-after :dir) seed-after)
    
    (assert (= (fset:lookup p-after :h) 100))
    (assert (= (fset:lookup p-after :x) 64000))
    (assert (= (fset:lookup p-after :y) 160000))
    (assert (= (fset:lookup p-after :dir) 1))
    (assert (= seed-after 1668141782))
    (format t "  PASS: Deterministic respawn match~%")))

(defun assert-eq (got expected label)
  (if (equal got expected)
      (format t "  PASS: ~A (~A == ~A)~%" label got expected)
      (progn
        (format t "  FAIL: ~A (got ~A, expected ~A)~%" label got expected)
        (uiop:quit 1))))

(defun assert-true (val label)
  (if val
      (format t "  PASS: ~A~%" label)
      (progn
        (format t "  FAIL: ~A (got NIL)~%" label)
        (uiop:quit 1))))

(defun test-jnb-serialize ()
  (format t "~%Testing Jump and Bump Serialization (Lisp)...~%")
  ;; 2 players, one alive, one dead
  (let* ((p0 (make-jnb-player :id 0 :x 64000 :y 160000 :vx 250 :vy -500 :h 100 :dir 0 :on-ground t :k 3))
         (p1 (make-jnb-player :id 1 :x 128000 :y 80000 :vx -100 :vy 500 :h 0 :dir 1 :on-ground nil :k 1))
         (state (fset:map (:tick 42)
                          (:players (fset:map (0 p0) (1 p1)))
                          (:custom-state (fset:map (:seed 9999)))))
         (json-str (jnb-serialize state nil))
         (parsed (yason:parse json-str)))
    (format t "  serialize: ~A~%" json-str)
    (assert-eq (gethash "TICK" parsed) 42 "Serialize: TICK present")
    (assert-eq (gethash "SEED" parsed) 9999 "Serialize: SEED present")
    (assert-true (gethash "PLAYERS" parsed) "Serialize: PLAYERS present")
    (let ((players (gethash "PLAYERS" parsed)))
      (assert-eq (length players) 2 "Serialize: 2 players")
      (let ((pp0 (find-if (lambda (p) (= (gethash "ID" p) 0)) players))
            (pp1 (find-if (lambda (p) (= (gethash "ID" p) 1)) players)))
        (assert-true pp0 "Serialize: player 0 found")
        (assert-true pp1 "Serialize: player 1 found")
        (assert-eq (gethash "X" pp0) 64000 "Serialize: p0 X")
        (assert-eq (gethash "Y" pp0) 160000 "Serialize: p0 Y")
        (assert-eq (gethash "VX" pp0) 250 "Serialize: p0 VX")
        (assert-eq (gethash "VY" pp0) -500 "Serialize: p0 VY")
        (assert-eq (gethash "HEALTH" pp0) 100 "Serialize: p0 HEALTH")
        (assert-eq (gethash "DIR" pp0) 0 "Serialize: p0 DIR")
        (assert-eq (gethash "ON_GROUND" pp0) 1 "Serialize: p0 ON_GROUND")
        (assert-eq (gethash "KILLS" pp0) 3 "Serialize: p0 KILLS")
        (assert-eq (gethash "HEALTH" pp1) 0 "Serialize: p1 HEALTH (dead)")
        (assert-eq (gethash "DIR" pp1) 1 "Serialize: p1 DIR")
        (assert-eq (gethash "ON_GROUND" pp1) 0 "Serialize: p1 ON_GROUND (airborne)")
        (assert-eq (gethash "KILLS" pp1) 1 "Serialize: p1 KILLS")))))

(test-jnb-gravity)
(test-jnb-squish)
(test-jnb-respawn)
(test-jnb-serialize)

(format t "~%All Lisp Jump and Bump Cross-Platform Tests Passed!~%")
(uiop:quit)
