(in-package #:foldback)

;; --- Air Hockey Constants (Fixed-Point) ---
(defparameter +ah-table-width+  8000)
(defparameter +ah-table-height+ 12000)
(defparameter +ah-paddle-radius+ 400)
(defparameter +ah-puck-radius+   300)
(defparameter +ah-goal-width+    2000)
(defparameter +ah-max-score+ 11)
(defparameter +ah-friction+ 990) ; 0.99
(defparameter +ah-bounce+ 800)   ; 0.8
(defparameter +ah-corner-radius+ 1000)

(defun make-ah-player (id x y)
  (fset:map (:id id) (:x x) (:y y) (:vx 0) (:vy 0) (:score 0)))

(defun make-ah-puck (x y)
  (fset:map (:x x) (:y y) (:vx 0) (:vy 0)))

(defun generate-table-segments ()
  (let* ((half-w (fp-to-float (/ +ah-table-width+ 2)))
         (half-h (fp-to-float (/ +ah-table-height+ 2)))
         (cr (fp-to-float +ah-corner-radius+))
         (gw (fp-to-float (/ +ah-goal-width+ 2)))
         (segments '()))

    (labels ((add-seg (x1 y1 x2 y2 type)
              (push (fset:map (:x1 (fp-from-float x1)) 
                              (:y1 (fp-from-float y1)) 
                              (:x2 (fp-from-float x2)) 
                              (:y2 (fp-from-float y2)) 
                              (:type type)) 
                    segments))
            (add-corner (cx cy start-angle end-angle)
              (let ((steps 6))
                (loop for i from 0 below steps
                      for a1 = (+ start-angle (* i (/ (- end-angle start-angle) steps)))
                      for a2 = (+ start-angle (* (1+ i) (/ (- end-angle start-angle) steps)))
                      do (add-seg (+ cx (* cr (cos a1))) (+ cy (* cr (sin a1)))
                                  (+ cx (* cr (cos a2))) (+ cy (* cr (sin a2)))
                                  :wall)))))

      (let ((xL (- half-w)) (xR half-w) (yT (- half-h)) (yB half-h))
        ;; Straight Walls
        (add-seg xL (- yB cr) xL (+ yT cr) :wall)
        (add-seg xR (+ yT cr) xR (- yB cr) :wall)
        (add-seg (- xR cr) yT gw yT :wall)
        (add-seg (- gw) yT (+ xL cr) yT :wall)
        (add-seg gw yT (- gw) yT :goal-top)
        (add-seg (+ xL cr) yB (- gw) yB :wall)
        (add-seg gw yB (- xR cr) yB :wall)
        (add-seg (- gw) yB gw yB :goal-bottom)

        ;; Corners
        (add-corner (- xR cr) (+ yT cr) (* 1.5 pi) (* 2.0 pi))
        (add-corner (+ xL cr) (+ yT cr) pi (* 1.5 pi))
        (add-corner (+ xL cr) (- yB cr) (* 0.5 pi) pi)
        (add-corner (- xR cr) (- yB cr) 0.0 (* 0.5 pi))))
    (nreverse segments)))

(defparameter *ah-segments* (generate-table-segments))

(defun airhockey-join (player-id state)
  (let ((players (fset:lookup state :players)))
    (if (>= (fset:size players) 2)
        nil
        (cond
          ((= (fset:size players) 0) (make-ah-player player-id 0 -4000))
          ((= (fset:size players) 1) (make-ah-player player-id 0 4000))
          (t nil)))))

(defun airhockey-reset-positions (state &optional new-tick)
  (let* ((players (fset:lookup state :players))
         (new-players (fset:map)))
    (fset:do-map (pid p players)
      (let ((ny (if (= pid 0) -4000 4000)))
        (setf new-players (fset:with new-players pid 
                                    (fset:with (fset:with p :x 0) :y ny)))))
    (let ((ns (fset:with (fset:with state :players new-players)
                         :puck (make-ah-puck 0 0))))
      (if new-tick (fset:with ns :tick new-tick) ns))))

(defun airhockey-update (state inputs)
  (let* ((players (fset:lookup state :players))
         (puck (fset:lookup state :puck))
         (tick (or (fset:lookup state :tick) 0))
         (status (or (fset:lookup state :status) :waiting))
         (new-players (fset:map))
         (new-puck puck))

    (when (and (eq status :waiting) (>= (fset:size players) 2))
      (setf status :active)
      (let ((ns (fset:with state :status :active)))
        (setf state (airhockey-reset-positions ns))
        (setf players (fset:lookup state :players))
        (setf new-puck (fset:lookup state :puck))))

    (if (not (eq status :active))
        (return-from airhockey-update (fset:with state :tick (1+ tick)))
        nil)

    ;; 2. Update Players (Paddle Movement)
    (fset:do-map (pid p players)
      (let* ((input (or (and inputs (fset:lookup inputs pid)) (fset:map)))
             (target-x (or (fset:lookup input :tx) (fset:lookup p :x)))
             (target-y (or (fset:lookup input :ty) (fset:lookup p :y)))
             (half-w (/ +ah-table-width+ 2))
             (half-h (/ +ah-table-height+ 2))
             (min-x (+ (- half-w) +ah-paddle-radius+))
             (max-x (- half-w +ah-paddle-radius+))
             (min-y (if (= pid 0) (+ (- half-h) +ah-paddle-radius+) +ah-paddle-radius+))
             (max-y (if (= pid 0) (- +ah-paddle-radius+) (- half-h +ah-paddle-radius+)))
             (nx (fp-clamp target-x min-x max-x))
             (ny (fp-clamp target-y min-y max-y))
             (vx (fp-sub nx (fset:lookup p :x)))
             (vy (fp-sub ny (fset:lookup p :y))))
        (let ((new-p (fset:with p :x nx)))
          (setf new-p (fset:with new-p :y ny))
          (setf new-p (fset:with new-p :vx vx))
          (setf new-p (fset:with new-p :vy vy))
          (setf new-players (fset:with new-players pid new-p)))))

    ;; 3. Update Puck Physics
    (let* ((px (fset:lookup new-puck :x))
           (py (fset:lookup new-puck :y))
           (pvx (fset:lookup new-puck :vx))
           (pvy (fset:lookup new-puck :vy)))
      
      (setf pvx (fp-mul pvx +ah-friction+))
      (setf pvy (fp-mul pvy +ah-friction+))
      (setf px (fp-add px pvx))
      (setf py (fp-add py pvy))

      ;; OOB CHECK
      (when (or (> (abs px) 4400) (> (abs py) 6600))
        (return-from airhockey-update (airhockey-reset-positions state (1+ tick))))

      ;; Paddle Collisions (using shared helper)
      (fset:do-map (pid p new-players)
        (declare (ignore pid))
        (let ((ppx (fset:lookup p :x))
              (ppy (fset:lookup p :y)))
          (when (fp-circles-overlap-p px py +ah-puck-radius+ ppx ppy +ah-paddle-radius+)
            (multiple-value-bind (nx ny overlap) 
                (fp-push-circles px py +ah-puck-radius+ ppx ppy +ah-paddle-radius+)
              (setf px (fp-add px (fp-mul nx overlap)))
              (setf py (fp-add py (fp-mul ny overlap)))
              (setf pvx (fp-add (fset:lookup p :vx) (fp-mul nx 50)))
              (setf pvy (fp-add (fset:lookup p :vy) (fp-mul ny 50)))))))

      ;; Wall / Goal Collisions (using shared helper)
      (dolist (seg *ah-segments*)
        (let* ((x1 (fset:lookup seg :x1)) (y1 (fset:lookup seg :y1))
               (x2 (fset:lookup seg :x2)) (y2 (fset:lookup seg :y2))
               (type (fset:lookup seg :type)))
          (multiple-value-bind (closest-x closest-y) (fp-closest-point-on-segment px py x1 y1 x2 y2)
            (let ((dist-sq (fp-dist-sq px py closest-x closest-y))
                  (rad-sq (fp-mul +ah-puck-radius+ +ah-puck-radius+)))
              (when (< dist-sq rad-sq)
                (cond
                  ((eq type :wall)
                   (let* ((dist (fp-sqrt dist-sq))
                          (nx (if (zerop dist) 0 (fp-div (fp-sub px closest-x) dist)))
                          (ny (if (zerop dist) 0 (fp-div (fp-sub py closest-y) dist)))
                          (overlap (fp-sub +ah-puck-radius+ dist)))
                     (setf px (fp-add px (fp-mul nx overlap)))
                     (setf py (fp-add py (fp-mul ny overlap)))
                     (let ((dot (fp-add (fp-mul pvx nx) (fp-mul pvy ny))))
                       (setf pvx (fp-mul (fp-sub pvx (fp-mul (fp-mul 2000 nx) dot)) +ah-bounce+))
                       (setf pvy (fp-mul (fp-sub pvy (fp-mul (fp-mul 2000 ny) dot)) +ah-bounce+)))))
                  ((eq type :goal-top)
                   (let ((p1 (fset:lookup new-players 1)))
                     (setf new-players (fset:with new-players 1 (fset:with p1 :score (1+ (fset:lookup p1 :score)))))
                     (if (>= (fset:lookup (fset:lookup new-players 1) :score) +ah-max-score+)
                         (setf status :p1-wins)
                         (return-from airhockey-update (airhockey-reset-positions (fset:with state :players new-players) (1+ tick))))))
                  ((eq type :goal-bottom)
                   (let ((p0 (fset:lookup new-players 0)))
                     (setf new-players (fset:with new-players 0 (fset:with p0 :score (1+ (fset:lookup p0 :score)))))
                     (if (>= (fset:lookup (fset:lookup new-players 0) :score) +ah-max-score+)
                         (setf status :p0-wins)
                         (return-from airhockey-update (airhockey-reset-positions (fset:with state :players new-players) (1+ tick))))))))))))

      (setf new-puck (fset:map (:x px) (:y py) (:vx pvx) (:vy pvy))))

    (let ((final-state (fset:with state :tick (1+ tick))))
      (setf final-state (fset:with final-state :players new-players))
      (setf final-state (fset:with final-state :status status))
      (setf final-state (fset:with final-state :puck new-puck))
      final-state)))

(defun airhockey-serialize (state last-state)
  (declare (ignore last-state))
  (let* ((players (fset:lookup state :players))
         (puck (fset:lookup state :puck))
         (tick (fset:lookup state :tick))
         (status (or (fset:lookup state :status) :waiting))
         (parts (list (cl:format nil "\"t\":~A" tick)
                      (cl:format nil "\"s\":\"~A\"" status))))
    (when puck
       (push (cl:format nil "\"pk\":{\"x\":~A,\"y\":~A,\"vx\":~A,\"vy\":~A}" (fset:lookup puck :x) (fset:lookup puck :y) (fset:lookup puck :vx) (fset:lookup puck :vy)) parts))
    (let ((p-list nil))
      (fset:do-map (id p players)
        (push (cl:format nil "{\"id\":~A,\"x\":~A,\"y\":~A,\"vx\":~A,\"vy\":~A,\"sc\":~A}" id (fset:lookup p :x) (fset:lookup p :y) (fset:lookup p :vx) (fset:lookup p :vy) (fset:lookup p :score)) p-list))
      (when p-list (push (cl:format nil "\"p\":[~{~A~^,~}]" (nreverse p-list)) parts)))
    (cl:format nil "{~{~A~^,~}}" (nreverse parts))))
